# frozen_string_literal: true
require 'support/azure/rest'
require 'support/azure/response'
require 'support/azure/service'
require 'support/azure/management'
require 'support/azure/vault'
require 'support/azure/graph'
require 'support/azure/storage_service'
require 'support/azure/queue_service'
require 'support/azure/blob_service'
require 'support/azure/deprecations/strings_in_where_clause'
